import './App.css';
import { useState } from 'react';
//using the react icons library by installing the plugin in the terminal/command line
//npm i react-icons -- save
import { TbWorldSearch } from "react-icons/tb";

/* Before you can run the app you need to install moment in the terminal/command line
  npm install moment-timezone --save is the plugin to use
*/

function App() {
  //Variables to be used in the project
  const [time, setTime] = useState('');
  // variables to generate a list of all timezones and store it in a variable
  const moment = require('moment-timezone');
  const timeZones = moment.tz.names();
  // console.log(timeZones);  -- test

  const [picked, setPicked] = useState('');

  //Const function to utilize the chosen timezone and add it to the picked variable
  const chosenTimeZone = (e) => {
    e.preventDefault();
    //test for if the timezone has been found and read by the function
    console.log(e);
    setPicked(e);
    //test for variable being changed
    console.log("Chosen Timezone: " + picked);
    //set the timezone from the moment libary to match the picked option
    moment.tz.setDefault({ picked });
    var t = moment();
    //test if this has been successful
    console.log(t);
  }

  /*const function to call the time generated by the picked variable
    and set it to a variable called setTime */
  const setTheTime = () => {
    moment.tz.setDefault(picked);
    var t = moment().format('h:m:s a');
    //for format - h = hour, m = minutes, s= seconds and a is am/pm
    setTime(t);
    console.log(t);

  }
  return (
    <div className="App">
      <header className="App-header">
        WORLDWIDE DIGITAL CLOCK APP
      </header>
      <body>
        {/* Form to allow user to choose a timezone and it to be generated */}
        <form onSubmit={chosenTimeZone}>
          {/* Dropdown menu to choose timezone */}
          <label className='lbl'> <b> Choose a timezone: </b>
            <select onChange={(e) => setPicked(e.target.value)}>
              {
                timeZones.map((x, y) =>
                  <option key={y}>{x}</option>
                )
              }
            </select>
          </label> <br />
          {/* Allows the picked timezone to be shown */}
          <label className='lbl'>
            <b>Timezone: </b>{picked} <br />
          </label>
          {/* Shows the correct time generated by the button click in a 12 hour time format*/}
          <label className='lbl'>
            <b> Time: </b>{time}
          </label>
        </form>
        <button onClick={setTheTime} id="btn"> <TbWorldSearch size={42} /> </button>

      </body>
    </div>//div
  );
}

export default App;
